### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by bastienk** [salesforce/cloudsplaining#119]
Hello,

When trying to generate a report I am getting the following error:
```
root@35283a410343:/# cloudsplaining scan --exclusions-file exclusions.yml --input-file default.json
        Excluded suffix: *servicerolepolicy
        Excluded suffix: *servicerolepolicy
        Excluded suffix: *servicerolepolicy
        Excluded prefix: /aws-service-role*
        Excluded suffix: *servicerolepolicy
        Excluded suffix: *servicerolepolicy
        Excluded suffix: *servicerolepolicy
        Excluded prefix: /aws-service-role*
        Excluded prefix: /aws-service-role*
        Excluded prefix: /aws-service-role*
        Excluded prefix: /aws-service-role*
        Excluded prefix: /aws-service-role*
        Excluded prefix: /aws-service-role*
        Excluded prefix: /aws-service-role*
Traceback (most recent call last):
  File "/usr/local/bin/cloudsplaining", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/bin/cli.py", line 32, in main
    cloudsplaining()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/command/scan.py", line 87, in scan
    account_authorization_details_cfg, exclusions, account_name, output, write_data_files=True
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/command/scan.py", line 152, in scan_account_authorization_details
    results = authorization_details.results
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/scan/authorization_details.py", line 56, in results
    "aws_managed_policies": self.policies.json_large_aws_managed,
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/scan/managed_policy_detail.py", line 73, in json_large_aws_managed
    result[policy.policy_id] = policy.json_large
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/scan/managed_policy_detail.py", line 204, in json_large
    InfrastructureModification=self.policy_document.infrastructure_modification,
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/scan/policy_document.py", line 76, in infrastructure_modification
    statement.missing_resource_constraints_for_modify_actions()
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/scan/statement_detail.py", line 266, in missing_resource_constraints_for_modify_actions
    exclusions
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/scan/statement_detail.py", line 241, in missing_resource_constraints
    self.expanded_actions
  File "/usr/local/lib/python3.6/site-packages/cloudsplaining/shared/utils.py", line 35, in remove_wildcard_only_actions
    if len(action_data[service_prefix]) == 0:
TypeError: 'bool' object is not subscriptable
```

This is how I run it:
```
cloudsplaining download --profile default
cloudsplaining create-exclusions-file
cloudsplaining scan --exclusions-file exclusions.yml --input-file default.json
```

The exclusions and input files are correctly generated. Cloudsplaining has been installed with pip3 following the instructions in your readme.

I tried version 0.1.8/0.2.0/0.2.1 with Python 3.6/3.7/3.8.
What am I doing wrong? Thank you!

**Comment by kmcquade** [comment]
Hey @bastienk, I think I encountered this and fixed it in version 0.2.2. Can you try with that one and see if it works?

**Comment by kmcquade** [comment]
@bastienk oh oops. I guess I forgot to push the new release. Should be coming shortly. One sec

**Comment by kmcquade** [comment]
@bastienk - pushed the new release. Should be installable via pip and Homebrew in about 5-10 min after the automation runs.

Let me know if this fixes your problem.

**Comment by bastienk** [comment]
@kmcquade it works now, thank you for your help!
