### ISSUE TITLE
ERROR TypeError: can only join an iterable

### ISSUE THREAD

**Issue by nmarchini** [salesforce/cloudsplaining#142]
I get the following error when running this tool. it was installed via homebrew with no errors

````
cloudsplaining scan-policy-file --input-file iam.json
Potential Issue found: Policy is capable of Privilege Escalation
- Method: AttachUserPolicy
Traceback (most recent call last):
  File "/usr/local/bin/cloudsplaining", line 33, in <module>
    sys.exit(load_entry_point('cloudsplaining==0.2.3', 'console_scripts', 'cloudsplaining')())
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/cloudsplaining/bin/cli.py", line 32, in main
    cloudsplaining()
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.2.3/libexec/lib/python3.9/site-packages/cloudsplaining/command/scan_policy_file.py", line 87, in scan_policy_file
    print(f"  Actions: {', '.join(item.get('PrivilegeEscalation'))}\n")
TypeError: can only join an iterable

**Comment by saikirankv** [comment]
@nmarchini can you share the iam.json file that you passed to cli?

**Comment by nmarchini** [comment]
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "BlockUsersandGroups",
            "Effect": "Deny",
            "Action": [
                "iam:AddUserToGroup",
                "iam:AttachGroupPolicy",
                "iam:AttachUserPolicy",
                "iam:CreateGroup",
                "iam:CreateUser",
                "iam:DeleteGroup",
                "iam:DeleteGroupPolicy",
                "iam:DeleteUser",
                "iam:DeleteUserPermissionsBoundary",
                "iam:DeleteUserPolicy",
                "iam:DetachGroupPolicy",
                "iam:DetachUserPolicy",
                "iam:PutGroupPolicy",
                "iam:PutUserPermissionsBoundary",
                "iam:PutUserPolicy",
                "iam:RemoveUserFromGroup",
                "iam:TagUser",
                "iam:UntagUser",
                "iam:UpdateGroup",
                "iam:UpdateUser"
            ],
            "Resource": "*",
            "Condition": {
                "ArnNotEquals": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::*:role/CCS_Administrator"
                    ]
                }
            }
        },
        {
            "Sid": "BlockProtectedRoles",
            "Effect": "Deny",
            "Action": [
                "iam:AttachRolePolicy",
                "iam:DeleteRole",
                "iam:DeleteRolePermissionsBoundary",
                "iam:DeleteRolePolicy",
                "iam:DetachRolePolicy",
                "iam:PutRolePermissionsBoundary",
                "iam:PutRolePolicy",
                "iam:TagRole",
                "iam:UntagRole",
                "iam:UpdateAssumeRolePolicy",
                "iam:UpdateRole",
                "iam:UpdateRole",
                "iam:UpdateRoleDescription"
            ],
            "Resource": [
                "arn:aws:iam::*:role/CCS*",
                "arn:aws:iam::*:role/CUST*"
            ],
            "Condition": {
                "ArnNotEquals": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::*:role/CCS_Administrator"
                    ]
                }
            }
        },
        {
            "Sid": "BlockPermissionElevation",
            "Effect": "Deny",
            "Action": [
                "iam:AttachRolePolicy",
                "iam:DetachRolePolicy"
            ],
            "Resource": "*",
            "Condition": {
                "ForAllValues:ArnEquals": {
                    "iam:PolicyARN": [
                        "arn:aws:iam::aws:policy/AdministratorAccess",
                        "arn:aws:iam::aws:policy/PowerUserAccess",
                        "arn:aws:iam::aws:policy/IAMFullAccess"
                    ]
                },
                "ArnNotEquals": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::*:role/CCS_Administrator"
                    ]
                }
            }
        },
        {
            "Sid": "BlockRemoveProtectedPolicyFromProtectedRole",
            "Effect": "Deny",
            "Action": [
                "iam:AttachRolePolicy",
                "iam:DetachRolePolicy"
            ],
            "Resource": [
                "arn:aws:iam::*:role/CCS*",
                "arn:aws:iam::*:role/CUST*"
            ],
            "Condition": {
                "ForAllValues:ArnEquals": {
                    "iam:PolicyARN": [
                        "arn:aws:iam::*:policy/CUST*",
                        "arn:aws:iam::*:policy/CCS*"
                    ]
                },
                "ArnNotEquals": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::*:role/CCS_Administrator"
                    ]
                }
            }
        }
    ]
}
```

**Comment by kmcquade** [comment]
@nmarchini - this should be fixed in the latest release. Can you try testing and let me know if it works? thanks

**Comment by kmcquade** [comment]
@nmarchini - I am going to go ahead and close this. If you have any more issues, feel free to reopen

**Comment by nmarchini** [comment]
That fixed it, thanks
