### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3981: character maps to <undefined>

### ISSUE THREAD

**Issue by dc401** [salesforce/cloudsplaining#159]
Getting the following error with the latest pip3 installation of cloudsplaining on a Windows 10 host Python 3.9.1 64bit:
Runtime syntax: cloudsplaining.exe scan --input-file .\default.json

Methods to reproduce:

- Tried another Windows host with pip install
- Tried changing AWS accounts that had less complex roles or users

Other references:
https://gitter.im/cloudsplaining/community
https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character

```
Excluded prefix: service-role*
Excluded prefix: service-role*
Traceback (most recent call last):
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python39\Scripts\cloudsplaining.exe\__main__.py", line 7, in <module>
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\bin\cli.py", line 32, in main
    cloudsplaining()
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\command\scan.py", line 97, in scan
    rendered_html_report = scan_account_authorization_details(
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\command\scan.py", line 181, in scan_account_authorization_details
    rendered_report = html_report.get_html_report()
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\output\report.py", line 53, in get_html_report
    vendor_bundle_js=self.vendor_bundle,
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\output\report.py", line 46, in vendor_bundle
    bundle_content = f.read()
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3981: character maps to <undefined>
```

**Comment by kmcquade** [comment]
@dc401 - that is really strange. I haven't seen this before. I run this on Mac OS and Linux, but haven't run it on windows for a long time.

As a temporary measure, have you tried using the `--minimize` option? It looks like this is the section of code that loads the vendor.js bundle file, so if you use the `--minimize` option it will grab the vendor JS bundle files from CDN instead of embedding them into the HTML file. That might help.

**Comment by dennischow-fullstack** [comment]
Hi @kmcquade  thank you very much for the suggestion. That worked for me. Can the options features be updated a bit? I feel that things like this and the "--input-file" options aren't properly seen in the cloudsplaing --help default dialogue.

**Comment by kmcquade** [comment]
@dennischow-fullstack - glad it worked :)

The `cloudsplaining --help` default dialogue wouldn't show that option - it would be under `cloudsplaining scan --help`. When you run `cloudsplaining scan --help`, it shows the following text for the `--minimize` option: "Reduce the size of the HTML Report by pulling the Cloudsplaining Javascript code over the internet." You'll also notice the --input-file help there too. 

Is that what you are looking for? If you're looking for something else, it would help to get more details.
