### ISSUE TITLE
UnicodeDecodeError Running on Windows

### ISSUE THREAD

**Issue by loque1** [salesforce/cloudsplaining#181]
Hi. I am trying to run this on my windows account and I get the following error. 

```
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\cloudsplaining.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\cloudsplaining\bin\cli.py", line 34, in main
    cloudsplaining()
  File "c:\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\cloudsplaining\command\scan.py", line 106, in scan
    rendered_html_report = scan_account_authorization_details(
  File "c:\python39\lib\site-packages\cloudsplaining\command\scan.py", line 204, in scan_account_authorization_details
    rendered_report = html_report.get_html_report()
  File "c:\python39\lib\site-packages\cloudsplaining\output\report.py", line 54, in get_html_report
    vendor_bundle_js=self.vendor_bundle,
  File "c:\python39\lib\site-packages\cloudsplaining\output\report.py", line 47, in vendor_bundle
    bundle_content = f.read()
  File "c:\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3981: character maps to <undefined>
```
I have tried with multiple accounts and the same error occurred any help would be appriciated

**Comment by kmcquade** [comment]
@loque1 - this should be fixed in the most recent version. Take it for a spin and let me know if it works for you.
