### ISSUE TITLE
Json.decoder issue in windows

### ISSUE THREAD

**Issue by meverett91** [salesforce/cloudsplaining#197]
Looking for some help. Trying to scan a downloaded authorization details .json file. Getting the following error, I am on the latest version. Thanks!

```python
PS C:\Users\myuser> cloudsplaining scan -i .\test1.json -o .\Cloud\ -m
Traceback (most recent call last):
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python39\Scripts\cloudsplaining.exe\__main__.py", line 7, in <module>
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\bin\cli.py", line 34, in main
    cloudsplaining()
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\site-packages\cloudsplaining\command\scan.py", line 105, in scan
    account_authorization_details_cfg = json.loads(contents)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\myuser\appdata\local\programs\python\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kmcquade** [comment]
@meverett91 - are you sure the JSON is valid? Have you tried scanning that file from Cloudsplaining installed on Linux or WSL?

**Comment by kmcquade** [comment]
@meverett91 I'm going to close this due to inactivity - feel free to reopen if you run into this issue again. thanks.

**Comment by rusherr02** [comment]
Hey @kmcquade , I have one doubt, can't we pass `.yaml` file in this tool, I am getting the below error:

`cloudsplaining scan-policy-file --input-file CFT/AWSTemp.yaml                       
Traceback (most recent call last):
  File "/usr/local/bin/cloudsplaining", line 33, in <module>
    sys.exit(load_entry_point('cloudsplaining==0.5.1', 'console_scripts', 'cloudsplaining')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/cloudsplaining/bin/cli.py", line 34, in main
    cloudsplaining()
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/cloudsplaining/command/scan_policy_file.py", line 46, in scan_policy_file
    policy = json.load(json_file)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
➜  Desktop cloudsplaining scan-policy-file --input-file CFT/AWSTemplateFormatVersion:\ \'2010-09-09\'.json 
Traceback (most recent call last):
  File "/usr/local/bin/cloudsplaining", line 33, in <module>
    sys.exit(load_entry_point('cloudsplaining==0.5.1', 'console_scripts', 'cloudsplaining')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/cloudsplaining/bin/cli.py", line 34, in main
    cloudsplaining()
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cloudsplaining/0.5.1/libexec/lib/python3.11/site-packages/cloudsplaining/command/scan_policy_file.py", line 46, in scan_policy_file
    policy = json.load(json_file)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
