### ISSUE TITLE
IndexError: list index out of range. Please provide a valid ARN.

### ISSUE THREAD

**Issue by scoleri** [salesforce/cloudsplaining#229]
```
"account": elements[4],
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/cloudsplaining", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/cloudsplaining/bin/cli.py", line 34, in main
    cloudsplaining()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cloudsplaining/command/scan.py", line 105, in scan
    rendered_html_report = scan_account_authorization_details(
  File "/usr/lib/python3.9/site-packages/cloudsplaining/command/scan.py", line 185, in scan_account_authorization_details
    authorization_details = AuthorizationDetails(
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/authorization_details.py", line 44, in __init__
    self.group_detail_list = GroupDetailList(
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/group_details.py", line 33, in __init__
    self.groups = [
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/group_details.py", line 34, in <listcomp>
    GroupDetail(group_detail, policy_details, exclusions)
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/group_details.py", line 133, in __init__
    inline_policy = InlinePolicy(policy_detail)
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/inline_policy.py", line 29, in __init__
    self.policy_document = PolicyDocument(
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/policy_document.py", line 49, in __init__
    self.statements.append(StatementDetail(statement))
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/statement_detail.py", line 46, in __init__
    self.not_action_effective_actions = self._not_action_effective_actions()
  File "/usr/lib/python3.9/site-packages/cloudsplaining/scan/statement_detail.py", line 110, in _not_action_effective_actions
    actions_specific_to_arn = get_actions_matching_arn(arn)
  File "/usr/lib/python3.9/site-packages/policy_sentry/querying/actions.py", line 275, in get_actions_matching_arn
    raw_arns = get_matching_raw_arns(arn)
  File "/usr/lib/python3.9/site-packages/policy_sentry/querying/arns.py", line 122, in get_matching_raw_arns
    service_in_scope = get_service_from_arn(arn)
  File "/usr/lib/python3.9/site-packages/policy_sentry/util/arns.py", line 183, in get_service_from_arn
    result = parse_arn(arn)
  File "/usr/lib/python3.9/site-packages/policy_sentry/util/arns.py", line 173, in parse_arn
    raise Exception("The provided ARN is invalid. IndexError: %s. Please provide a valid ARN." % error) from error
Exception: The provided ARN is invalid. IndexError: list index out of range. Please provide a valid ARN.

✔ ~/Projects/cloudsplain [master|✚ 3…1]
10:46 $ cloudsplaining --version
cloudsplaining, version 0.4.6
```

**Comment by kmcquade** [comment]
@scoleri are there any details as to the actual ARN that failed?

**Comment by kmcquade** [comment]
@scoleri - try the latest version of Cloudsplaining - it should give you details on the ARN that failed. Let me know what that ARN is and we'll see what is breaking it.
