### ISSUE TITLE
TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by HenryHoggard** [salesforce/cloudsplaining#23]
Just having a play with this tool, getting the following error after executing the scan command.

```
cloudsplaining download
cloudsplaining scan --input default.json
```

```
Traceback (most recent call last):
  File "/usr/local/bin/cloudsplaining", line 30, in <module>
    cloudsplaining()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/command/scan.py", line 82, in scan
    scan_account_authorization_file(input, exclusions_cfg, output, all_access_levels, skip_open_report)
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/command/scan.py", line 118, in scan_account_authorization_file
    exclusions_cfg, modify_only=True
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/scan/authorization_details.py", line 233, in missing_resource_constraints
    return self.findings.json
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/output/findings.py", line 41, in json
    these_findings.append(finding.json)
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/output/findings.py", line 181, in json
    "PrivilegeEscalation": self.privilege_escalation,
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/output/findings.py", line 152, in privilege_escalation
    return self.policy_document.allows_privilege_escalation
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/scan/policy_document.py", line 80, in allows_privilege_escalation
    x.lower() for x in self.all_allowed_unrestricted_actions
  File "/usr/local/lib/python3.7/site-packages/cloudsplaining/scan/policy_document.py", line 53, in all_allowed_unrestricted_actions
    allowed_actions.extend(statement.expanded_actions)
TypeError: 'bool' object is not iterable
```

**Comment by kmcquade** [comment]
Interesting. I’ll address this shortly. Thanks for opening!

**Comment by kmcquade** [comment]
Mind jumping on the Gitter channel? I can throw you a tarball to install so we can test it against your JSON file without pushing a whole new release.

**Comment by kmcquade** [comment]
Never mind! Figured out how to reproduce the issue. Fix and release coming shortly. Added unit tests for it as well so this doesn't arise in the future.

Feel free to re-open after the fact if this does not fix your issue.
