### ISSUE TITLE
TypeError: list indices must be integers or slices, not str (Windows 10)

### ISSUE THREAD

**Issue by rodasugo** [salesforce/cloudsplaining#313]
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: /aws-service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
←[90m   Excluded prefix: service-role*←[0m
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\cloudsplaining.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\bin\cli.py", line 34, in main
    cloudsplaining()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\command\scan.py", line 82, in scan
    rendered_html_report = scan_account_authorization_details(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\command\scan.py", line 180, in scan_account_authorization_details
    results = authorization_details.results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\authorization_details.py", line 150, in results
    "inline_policies": self.inline_policies,
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\authorization_details.py", line 106, in inline_policies
    results.update(self.role_detail_list.inline_policies_json)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\role_details.py", line 117, in inline_policies_json
    results.update(role_detail.inline_policies_json)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\role_details.py", line 309, in inline_policies_json
    policies = {
               ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\role_details.py", line 310, in <dictcomp>
    policy.policy_id: policy.json_large for policy in self.inline_policies
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\inline_policy.py", line 175, in json_large
    "links": self.getFindingLinks(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\cloudsplaining\scan\inline_policy.py", line 72, in getFindingLinks
    links[
TypeError: list indices must be integers or slices, not str

I appreciate if you can help me!!!

**Comment by gruebel** [comment]
Hey @rodasugo thanks for reaching out.

Can you elaborate what exactly you did to get to this error and which version of `cloudsplaining` are you using?

**Comment by nabanita-bag** [comment]
the issue is here:


   def getFindingLinks(self, findings: List[Dict[str, Any]]) -> Dict[str, str]:
        links = {}
        for finding in findings:
            links[
                finding["type"]
            ] = f'https://cloudsplaining.readthedocs.io/en/latest/glossary/privilege-escalation/#{finding["type"]}'
        return links


But links is a dictionary already, with string type of key. Why is the compiler throwing an error?

**Comment by gruebel** [comment]
Feel free to reach out again with additional info.

**Comment by nabanita-bag** [comment]
> Feel free to reach out again with additional info.

Can you point me to the MR that solved this issue?

**Comment by gruebel** [comment]
@nabanita-bag there is none, because I don't have enough information to reproduce it.
