### ISSUE TITLE
Problem with download function

### ISSUE THREAD

**Issue by acidflash** [salesforce/cloudsplaining#62]
I try to do a `cloudsplaning download` after i have assume `export AWS_PROFILE=XXXX` a role to my account.

But i get this output:

`download --profile ss-privat
Found credentials in shared credentials file: ~/.aws/credentials
Enter MFA code for arn:aws:iam::XXXXXXX:mfa/XXXX: 
Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 516, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 264, in __call__
    return self._refresh()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 657, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 667, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 800, in _get_credentials
    return client.assume_role(**kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
Traceback (most recent call last):
  File "/usr/local/bin/cloudsplaining", line 33, in <module>
    sys.exit(load_entry_point('cloudsplaining==0.1.4', 'console_scripts', 'cloudsplaining')())
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/cloudsplaining/bin/cli.py", line 32, in main
    cloudsplaining()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/cloudsplaining/command/download.py", line 71, in download
    for page in paginator.paginate(Filter=["User"]):
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/signers.py", line 152, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/signers.py", line 232, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 605, in get_frozen_credentials
    self._refresh()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 500, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 516, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 264, in __call__
    return self._refresh()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 657, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 667, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 800, in _get_credentials
    return client.assume_role(**kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
`

**Comment by kmcquade** [comment]
@acidflash - the key line is here:

```
Found credentials in shared credentials file: ~/.aws/credentials Enter MFA code for arn:aws:iam::XXXXXXX:mfa/XXXX: Refreshing temporary credentials failed during mandatory refresh period.
```

Seems like you need to update your STS credentials for that profile.

**Comment by acidflash** [comment]
> @acidflash - see the first line:
> 
> `Found credentials in shared credentials file: ~/.aws/credentials Enter MFA code for arn:aws:iam::XXXXXXX:mfa/XXXX: Refreshing temporary credentials failed during mandatory refresh period.`
> 
> Same with the last line:
> 
> `"/usr/local/Cellar/cloudsplaining/0.1.4/libexec/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.`
> 
> Seems like you need to update your STS credentials for that profile.

Unfortunately, that is not the fault. When I use exactly the same profile when I do everything else in TF or other programs against AWS.
So the question really is whether cloudsplaining works with assume profile?
However, I can test to do new access key against that account and test run.

**Comment by kmcquade** [comment]
Hmmm. Ok. Would you mind elaborating more on your setup? If it’s running on your machine, whether you are using an SSO login command with AWS CLI, what the credentials file looks like, or anything else relevant. 

I rely on boto3/botocore to handle the AWS login - and so far, it handles the usage and prioritization of credential loading methods (environment variables, EC2 metadata, credentials files). I assumed (no pun intended) that boto3 would also handle profiles that assume other roles, so this one has me a bit puzzled.

All the code for the download command is here, by the way. https://github.com/salesforce/cloudsplaining/blob/master/cloudsplaining/command/download.py#L46. 

If anyone has some ideas as to the problem here, I’m all ears.

**Comment by acidflash** [comment]
Of course.
I'm using MacOSX 10.15.5 and have aws-cli/2.0.26 Python/3.8.3 Darwin/19.5.0 botocore/2.0.0dev30 installed with brew.
We use assume roles so in my credentials file I only have:
`cat credentials`
`[XX-XXX]`
`aws_access_key_id = XXX`
`aws_secret_access_key = XXX `

`cat config`
`[profile privat]`
`region=eu-north-1`
`source_profile=XX-XXX`
`role_arn=arn:aws:iam::123456789123:role/security`
`mfa_serial=arn:aws:iam::321987654321:mfa/acidflash`

And when i change my profile i just use `export AWS_PROFILE=privat`
`echo $AWS_PROFILE`
And the output is
`privat`

Don't know if terraforming also runs with the same library for managing login, because it has similar problems when I try to use it.

Should I put an access key directly on account, it works, but when we do not work that way, there will be problems in our audit.

So in order to get the same thing started in any test, you have to have two AWS accounts. And a trust between them for which you can assume the role.
IAM account should be in account1 and in account2 there should only be one role and no IAM user.

I hope this information can give you more clarity on how my setup looks.

**Comment by kmcquade** [comment]
Right on. I’ll test some stuff out and get back to you. Quite puzzling.

Did you install Cloudsplaining with pip or with Homebrew?

**Comment by acidflash** [comment]
> Right on. I’ll test some stuff out and get back to you. Quite puzzling.
> 
> Did you install Cloudsplaining with pip or with Homebrew?

Homebrew

**Comment by acidflash** [comment]
I can give some new input in this case.
I found if i run:
`aws-vault exec ss-privat`
`bash-3.2$ cloudsplaining download`
`Found credentials in environment variables.`
`Saved results to default.json`

So the i don´t know if this is a issue in aws-vault or cloudsplaining.

**Comment by kmcquade** [comment]
@acidflash , it looks like from what you showed above, it saved the Account authorization details to the default.json. Did that not work?

**Comment by kmcquade** [comment]
Just took a look at your original question. Instead of using `export AWS_PROFILE='profilename'`, use this instead:

```bash
cloudsplaining download --profile profilename
``` 

That should work.

**Comment by kmcquade** [comment]
@acidflash - any chance you were able to try the above?

Hoping to clean up some of the remaining issues.

**Comment by acidflash** [comment]
@kmcquade sorry for late response. 
I did just try it out with `cloudsplaining download --profile profilename` and it worked out just fine. So my issue is gone.
Thank you for solving this issue.
